// OpenKan Docs — editable Markdown workspace with live preview and agent generation.
(() => {
  "use strict";
  const { api } = window.OpenKanAPI;
  let state = null;
  const esc = (v) => String(v ?? "").replace(/[&<>"']/g, (c) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" })[c]);
  const flatten = (entries, out = []) => { for (const e of entries || []) e.isDir ? flatten(e.children, out) : out.push(e); return out; };
  const askPath = (value = "") => prompt("Document path relative to docs/", value)?.trim().replace(/^\/+/, "").replace(/\.\./g, "");
  const toolbar = () => `<header class="docs-workspace-head"><div><span class="workspace-eyebrow">Knowledge workspace</span><h2>Docs</h2><p>Write in Markdown, inspect the live document, or ask your configured agent to draft a guide.</p></div><div class="docs-actions"><button data-doc-action="new">New document</button><button data-doc-action="generate">Generate with agent</button><button data-doc-action="help">Formatting help</button></div></header>`;
  const formatBar = () => `<div class="docs-format-bar" aria-label="Formatting"><button data-doc-format="bold" title="Bold"><b>B</b></button><button data-doc-format="italic" title="Italic"><i>I</i></button><button data-doc-format="h2" title="Heading">H2</button><button data-doc-format="ul" title="Bulleted list">• List</button><button data-doc-format="ol" title="Numbered list">1. List</button><button data-doc-format="link" title="Link">↗</button><button data-doc-format="code" title="Code">&lt;/&gt;</button></div>`;
  function render() {
    if (!state) return;
    const files = flatten(state.entries);
    const editor = state.preview
      ? `<article class="docs-rendered docs-preview-editable" contenteditable="true" spellcheck="true" data-doc-preview aria-label="Editable document preview">${state.html || "<p>Nothing to preview.</p>"}</article>`
      : `<textarea id="docs-editor-input" spellcheck="true" placeholder="# Start writing…">${esc(state.content)}</textarea>`;
    state.root.innerHTML = `${toolbar()}<div class="docs-workspace"><aside class="docs-sidebar"><div class="docs-sidebar-title"><span>docs/</span><button data-doc-action="new" title="New document">+</button></div><p class="docs-sidebar-hint">Right-click a document for actions.</p><div class="docs-file-list">${files.map((f) => `<button class="${f.path === state.path ? "active" : ""}" data-doc-path="${esc(f.path)}">${esc(f.path)}</button>`).join("") || "<p>No documents yet.</p>"}</div></aside><main class="docs-editor"><header><div><strong>${esc(state.path || "Untitled document")}</strong><span>${state.dirty ? "Unsaved changes" : "Saved"}</span></div><div><button data-doc-action="preview">${state.preview ? "Markdown source" : "Live preview"}</button><button data-doc-action="save" ${state.path ? "" : "disabled"}>Save</button><button data-doc-action="delete" ${state.path ? "" : "disabled"}>Delete</button></div></header>${state.preview ? formatBar() : ""}${editor}</main></div><div id="docs-context-menu" class="docs-context-menu" hidden></div>`;
    state.root.querySelectorAll("[data-doc-path]").forEach((b) => b.onclick = () => load(b.dataset.docPath));
    state.root.querySelectorAll("[data-doc-action]").forEach((b) => b.onclick = () => action(b.dataset.docAction));
    state.root.querySelector("#docs-editor-input")?.addEventListener("input", (e) => { state.content = e.target.value; state.dirty = true; state.root.querySelector(".docs-editor header span").textContent = "Unsaved changes"; });
    state.root.querySelector("[data-doc-preview]")?.addEventListener("input", (e) => { state.content = e.currentTarget.innerHTML; state.dirty = true; state.root.querySelector(".docs-editor header span").textContent = "Unsaved changes"; });
    state.root.querySelectorAll("[data-doc-format]").forEach((b) => b.onclick = () => applyFormat(b.dataset.docFormat));
    state.root.oncontextmenu = contextMenu;
  }
  async function renderPreview() { state.html = await api("POST", "/api/chat/render-markdown", { markdown: state.content }); }
  async function load(path) { const d = await api("GET", `/api/docs/${encodeURI(path)}?raw=0`); Object.assign(state, { path, content: d.raw || "", html: d.html || "", dirty: false, preview: false }); render(); }
  async function refresh() { const d = await api("GET", "/api/docs"); state.entries = d.entries || []; render(); }
  async function save() { if (!state.path) return; const d = await api("PUT", `/api/docs/${encodeURI(state.path)}`, { content: state.content }); state.html = d.html || state.html; state.dirty = false; await refresh(); }
  async function action(name) {
    if (name === "new") { const path = askPath("notes/new-document.md"); if (!path) return; Object.assign(state, { path, content: "# New document\n\n", html: "", dirty: true, preview: false }); render(); return; }
    if (name === "save") return save();
    if (name === "preview") { state.preview = !state.preview; if (state.preview) await renderPreview(); render(); return; }
    if (name === "delete" && state.path && confirm(`Delete ${state.path}?`)) { await api("DELETE", `/api/docs/${encodeURI(state.path)}`); Object.assign(state, { path:"", content:"", html:"", dirty:false }); return refresh(); }
    if (name === "generate") { const path = askPath(state.path || "guides/new-guide.md"); if (!path) return; const promptText = prompt("What should the configured agent write?", "Create a practical, complete guide."); if (!promptText) return; const model = prompt("Model (leave default to use workspace routing)", "default") || "default"; const effort = prompt("Reasoning effort: low, medium, high, or max", "high") || "high"; state.root.classList.add("is-generating"); try { const d = await api("POST", "/api/docs/generate", { path, prompt: promptText, model, effort, permissionMode: "bypassPermissions" }); Object.assign(state, { path, content:d.raw || "", html:d.html || "", dirty:false }); await refresh(); } finally { state.root.classList.remove("is-generating"); } return; }
    if (name === "help") alert("Markdown and preview editing\n\n# Heading\n**bold**  *italic*  `code`\n- bullet\n1. numbered\n[link](https://example.com)\n\nIn Live preview, select text and use the floating toolbar or right-click for formatting.");
  }
  function applyFormat(kind) { const preview = state.root.querySelector("[data-doc-preview]"); if (!preview) return; preview.focus(); const commands = { bold:"bold", italic:"italic", ul:"insertUnorderedList", ol:"insertOrderedList", code:"formatBlock" }; if (kind === "h2") document.execCommand("formatBlock", false, "h2"); else if (kind === "link") { const url = prompt("Link URL"); if (url) document.execCommand("createLink", false, url); } else if (kind === "code") document.execCommand("formatBlock", false, "pre"); else document.execCommand(commands[kind], false); preview.dispatchEvent(new InputEvent("input", { bubbles:true, inputType:"format" })); }
  function contextMenu(e) { const file = e.target.closest("[data-doc-path]"); const preview = e.target.closest("[data-doc-preview]"); if (!file && !preview) return; e.preventDefault(); const menu = state.root.querySelector("#docs-context-menu"); menu.hidden = false; menu.style.cssText = `left:${e.clientX}px;top:${e.clientY}px`; if (preview) { menu.innerHTML = `<button data-format="bold">Bold</button><button data-format="italic">Italic</button><button data-format="h2">Heading</button><button data-format="ul">Bulleted list</button><button data-format="link">Link</button>`; menu.onclick = (ev) => { menu.hidden = true; applyFormat(ev.target.dataset.format); }; return; } const path = file.dataset.docPath; menu.innerHTML = `<button data-menu="open">Open</button><button data-menu="rename">Rename</button><button data-menu="delete">Delete</button>`; menu.onclick = async (ev) => { const type = ev.target.dataset.menu; menu.hidden = true; if (type === "open") load(path); if (type === "delete" && confirm(`Delete ${path}?`)) { await api("DELETE", `/api/docs/${encodeURI(path)}`); await refresh(); } if (type === "rename") { const next = askPath(path); if (next) { const d = await api("GET", `/api/docs/${encodeURI(path)}?raw=1`); await api("PUT", `/api/docs/${encodeURI(next)}`, { content:d }); await api("DELETE", `/api/docs/${encodeURI(path)}`); await refresh(); } } }; }
  window.OpenKanDocs = { async mount(root) { state = { root, entries:[], path:"", content:"", html:"", dirty:false, preview:false }; await refresh(); }, unmount() { state = null; } };
})();
